#!/usr/bin/env python3
"""Print side-by-side comparison of profile data."""

print()
print('=' * 95)
print('  SIDE-BY-SIDE: Self CPU samples — directbufferpool vs mmap')
print('  (32 threads, 8KB blocks, 1MB file, sequentialReadBytesFromClone)')
print('=' * 95)
print()
print('DIRECTBUFFERPOOL (38,760 total self samples):')
print('  11,881  30.7%  HotPathReadBenchmarks.lambda (benchmark loop overhead)')
print('   9,187  23.7%  DirectByteBufferIndexInput.readByte')
print('   5,238  13.5%  MemorySessionImpl.checkValidStateRaw')
print('   3,436   8.9%  __psynch_cvwait  (kernel: pthread cond wait)')
print('   2,779   7.2%  Preconditions.checkIndex')
print('   2,212   5.7%  NativeMemorySegmentImpl.unsafeGetOffset')
print('     617   1.6%  AbstractMemorySegmentImpl.sessionImpl')
print('     517   1.3%  java_lang_Throwable::fill_in_stack_trace  (IOOBE!)')
print('     264   0.7%  BacktraceBuilder::push  (exception stack building)')
print('     190   0.5%  __psynch_cvsignal')
print()
print('MMAP (28,880 total self samples):')
print('  17,801  61.6%  MemorySegmentIndexInput.readByte')
print('   4,979  17.2%  __psynch_cvwait  (kernel: pthread cond wait)')
print('   3,616  12.5%  HotPathReadBenchmarks.lambda (benchmark loop overhead)')
print('   1,240   4.3%  ScopedMemoryAccess.getByteInternal')
print('     590   2.0%  __psynch_cvsignal')
print()
print('=' * 95)
print('  KEY FINDINGS FROM ACTUAL PROFILE DATA:')
print('=' * 95)
print()
print('1. MemorySegment bounds-check overhead is MASSIVE in directbufferpool:')
print('   - checkValidStateRaw:  5,238 samples (13.5%) vs 7 (0.0%) in mmap')
print('   - Preconditions.checkIndex: 2,779 (7.2%) vs 0 in mmap')
print('   - unsafeGetOffset: 2,212 (5.7%) vs 0 in mmap')
print('   - sessionImpl: 617 (1.6%) vs 0 in mmap')
print('   TOTAL bounds-check overhead: 10,846 samples = 28.0% of all CPU')
print()
print('   ROOT CAUSE: MMap segments from FileChannel.map() have constant size')
print('   known at JIT time. C2 hoists bounds checks out of the readByte loop.')
print('   DirectByteBuffer segments from MemorySegment.ofBuffer() are loaded')
print('   from SparseLongBlockTable on each block transition — C2 cannot prove')
print('   the segment reference or size is loop-invariant across the IOOBE')
print('   catch boundary, so bounds checks execute on EVERY readByte() call.')
print()
print('2. Exception overhead (IOOBE catch pattern):')
print('   - fill_in_stack_trace: 517 (1.3%)')
print('   - BacktraceBuilder::push: 264 (0.7%)')
print('   TOTAL: 781 samples = 2.0% of CPU on exception creation')
print('   MMap has ZERO exception overhead (Lucene uses guard long, not IOOBE)')
print()
print('3. readByte self-time tells the story:')
print('   - directbufferpool readByte: 9,187 (23.7%) — low because work leaks')
print('     into un-inlined bounds-check methods')
print('   - mmap readByte: 17,801 (61.6%) — high because the method is so')
print('     tight that nearly all samples land there (bounds checks eliminated)')
print()
print('4. Benchmark loop overhead:')
print('   - directbufferpool: 11,881 (30.7%) — the loop itself is hot because')
print('     readByte() is slow, so the loop+increment+branch is a larger')
print('     fraction of each iteration')
print('   - mmap: 3,616 (12.5%) — readByte is fast, loop overhead is small')
print()
print('=' * 95)
print('  WHAT TO PROVE NEXT (C2 inlining logs):')
print('=' * 95)
print()
print('Run: ./profile-quick-c2.sh')
print()
print('This will show C2 inlining decisions for readByte(). Expected to see:')
print('  - mmap: checkValidStateRaw/checkBounds INLINED into readByte')
print('  - directbufferpool: checkValidStateRaw/checkBounds NOT inlined')
print('    (too big, or segment reference not provably constant)')
print()
print('For kernel-level stacks (page faults, syscalls):')
print('Run: ./profile-kernel-stacks.sh')
print()
print('On macOS this needs DTrace (SIP may block kernel frames).')
print('On Linux, async-profiler uses perf_events automatically —')
print('no eBPF setup needed. Just: sudo sysctl kernel.perf_event_paranoid=1')
